base_url = "https://www.cflee.com"

title = "cflee.com"
description = "a weblog"

theme = "lightspeed"

compile_sass = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
netlify = false
