base_url = "https://www.cflee.com"

title = "cflee.com"
description = "a weblog"

compile_sass = true

generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

[extra]
netlify = false

# footer_links = [
#     {url = "xyz", name = "XYZ"},
# ]

rel_me_links = [
    "https://hachyderm.io/@cflee",
]
