[build]
publish = "public"
command = "zola build"

[build.environment]
# Set the version name that you want to use and Netlify will automatically use it.
ZOLA_VERSION = "0.14.0"

# The magic for deploying previews of branches.
# We need to override the base url with whatever url Netlify assigns to our
# preview site.  We do this using the Netlify environment variable
# `$DEPLOY_PRIME_URL`.
[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
ZOLA_VERSION = "0.14.0"


# redirect the domain aliases to canonical domain
[[redirects]]
from = "https://cflee.net/*"
to = "https://www.cflee.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.cflee.net/*"
to = "https://www.cflee.com/:splat"
status = 301
force = true