[build]
publish = "public"
command = "hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.48"
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.48"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.48"

# redirect the domain aliases to canonical domain
[[redirects]]
from = "https://cflee.net/*"
to = "https://www.cflee.com/:splat"
status = 301
force = true

[[redirects]]
from = "https://www.cflee.net/*"
to = "https://www.cflee.com/:splat"
status = 301
force = true
